AdoptionMVC/AdoptionMVC/Models/Animals.cs
using System.ComponentModel.DataAnnotations;
namespace AdoptionMVC.Models;

public class Animal
{
    public int Name { get; set; }
    public string IsAdopted { get; set; }
    public string Breed {  get; set; }
    public string Img { get; set; }


}

AdoptionMVC/AdoptionMVC/Models/Data/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
namespace AdoptionMVC.Models.Data;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {

    }

    //What tables are in my database
    public DbSet<Animal> Animals { get; set; }
}

AdoptionMVC/AdoptionMVC/Models/ErrorViewModel.cs
namespace AdoptionMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdoptionMVC/AdoptionMVC/Controllers/AnimalController.cs
using AdoptionMVC.Models;
using AdoptionMVC.Models.Data;
using Microsoft.AspNetCore.Mvc;
namespace AdoptionMVC.data;

public class AnimalController : Controller
{

    //Dependency injection  container DI for short
    private readonly AppDbContext _dbContext;//Controller is a class also a pattern to follow

    public AnimalController(AppDbContext dbContext)
    {
        _dbContext = dbContext;//by typing this out in this pattern it will give us a copy of the app dbcontext,DI, Like a fridge, go to the fridge and get me a fresh dbcontext.
    }
    
    [HttpPost]
    public IActionResult SearchAnimals(string breedInput)
    {
        //SELECT * FROM Animals WHERE Breed = breedInput
        return View();

        var animals = _dbContext.Animals.Where(x => x.Breed == breedInput).ToList();    
        return View(animals);
    }

}

AdoptionMVC/AdoptionMVC/Controllers/HomeController.cs
using AdoptionMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdoptionMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdoptionMVC/AdoptionMVC/Views/Animal/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

AdoptionMVC/AdoptionMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<form asp-action="SearchAnimals" asp-controller="Animal" method="post">
    <div class="form-group">
        <label for="simpleInput">Type in breed: </label>
        <input type="text" name="breedInput" />

    </div>
    <button type="submit">Submit</button>
</form>

AdoptionMVC/AdoptionMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdoptionMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdoptionMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdoptionMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AdoptionMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>